name: Deploy K3s Control Plane

on:
  workflow_dispatch:   # allows manual trigger from GitHub UI
  push:
    branches:
      - main           # run automatically when you push to main

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy server script to control plane
        run: |
          scp -o StrictHostKeyChecking=no ./scripts/server-install.sh desi@${{ secrets.SERVER_IP }}:/home/desi/server-install.sh

      - name: Run server script remotely
        run: |
          ssh -o StrictHostKeyChecking=no desi@${{ secrets.SERVER_IP }} "bash /home/desi/server-install.sh"
